### ISSUE TITLE
Display dates instead of week numbers

### ISSUE THREAD

**Issue by abailly** [bbougon/git-stats#30]
When one selects the `Weeks` tab, a weekly breakdown of the stats is displayed. 

<img width="671" alt="Screenshot 2023-07-08 at 09 16 37" src="https://github.com/bbougon/git-stats/assets/40221/23dcffbe-a9f9-49d9-bafe-986f422e1c8a">

It would probably be more useful if instead of `week 3` it said `2022-01-18` for example, eg. provide dates as the horizontal axis unit instead of week number.

**Comment by bbougon** [comment]
Hello,

thank you for the suggestion.
Displaying the week number instead of the date of the first day of the week is not the ideal solution. Nevertheless, it is more readable.

I'll try various format to display the date instead and see how it fits

**Comment by abailly** [comment]
Perhaps you could write the labels rotated by 90' ?

**Comment by bbougon** [comment]
Hello @abailly ,

sorry for the delay. 
The date format has been fixed on this commit `b9784227c066e64840ce68f06323acd5b150458e`.
Release 0.3.1 has been pushed on npm.

Here is a screenshot of the result:

<img width="1313" alt="Date format for weeks display" src="https://github.com/bbougon/git-stats/assets/5832143/d4e41408-ea40-4ddd-8e8e-3dfb61227429">

**Comment by bbougon** [comment]
Hello @abailly ,

sorry for the delay. 
The date format has been fixed on this commit `b9784227c066e64840ce68f06323acd5b150458e`.
Release 0.3.1 has been pushed on npm.

Here is a screenshot of the result:

<img width="1313" alt="Date format for weeks display" src="https://github.com/bbougon/git-stats/assets/5832143/d4e41408-ea40-4ddd-8e8e-3dfb61227429">
